Querz/mcaselector

src/main/java/net/querz/mcaselector/ui/StatusBar.java

Status bar tooltips are mixed up. This commit should fix it.

Fix Tooltips mixup

---

.gitignore
README.md
build.gradle
src/main/java/net/querz/mcaselector/headless/ParamExecutor.java
src/main/java/net/querz/mcaselector/io/ChunkImporter.java
src/main/java/net/querz/mcaselector/io/MCAChunkData.java
src/main/java/net/querz/mcaselector/io/MCAFile.java
src/main/java/net/querz/mcaselector/io/MCAFilePipe.java
src/main/java/net/querz/mcaselector/io/RegionImageGenerator.java
src/main/java/net/querz/mcaselector/tiles/Tile.java
src/main/java/net/querz/mcaselector/tiles/TileImage.java
src/main/java/net/querz/mcaselector/tiles/TileMap.java
src/main/java/net/querz/mcaselector/ui/ProgressDialog.java
src/main/java/net/querz/mcaselector/ui/ProgressTask.java
src/test/openjdk/Dockerfile
src/test/openjdk/docker-compose.yml

This fixes issues with importing chunks with an offset.
* Update absolute coordinates of structures, entities, tile entities and tile ticks. See https://github.com/Querz/mcaselector/issues/30#issuecomment-526645124 for a complete list.

Chunk import offset fix

---

README.md
src/main/java/net/querz/mcaselector/text/Translation.java
src/main/resources/lang/es_ES.txt

@NathanielFreeman Here is a pull request for the spanish translation.

Spanish translation

---

src/main/resources/lang/ru_RU.txt

Russian translation ru_RU.txt

---

src/main/resources/lang/sv_SE.txt

Changed some strings that should/shouldn't be in plural or singular and fixed some typos.

Fixed Swedish translation

---

src/main/resources/lang/pl_PL.txt

Polish language

---

README.md
build.gradle
travis/winrun4j/resource.rc

update version to 1.15.4

---

src/main/resources/lang/sv_SE.txt

Minor adjustments to the Swedish translations.

Fix Swedish translations

---

README.md
build.gradle
src/main/java/net/querz/mcaselector/ui/dialog/NBTEditorDialog.java
travis/winrun4j/resource.rc

This updates the version to 1.16.1. And fixes some typos.

Update version to 1.16.1

---

README.md
build.gradle
travis/winrun4j/resource.rc

Update version to 1.16.3

---

src/main/resources/lang/ja_JP.txt

Adjustment of Japanese translation

Fixed Japanese translation

---

src/main/resources/lang/tr_TR.txt

• Turkish Language Option Added.
---------------------------------------
• Türkçe Dil Seçeneği Eklendi.

Turkish Language Option Added.

---

src/main/resources/lang/tr_TR.txt

Some translation errors fixed

---

src/main/java/net/querz/mcaselector/tiles/ImagePool.java

Found this exception gets thrown repeatedly while deleting chunks. This PR just adds a simple check if the file still exists.

Fix FileNotFoundException when reading a regions last modified date

---

src/main/java/net/querz/mcaselector/key/KeyActivator.java
src/main/java/net/querz/mcaselector/tiles/TileMap.java
src/main/java/net/querz/mcaselector/ui/Window.java

Adds the ability to select chunks/regions one by one while dragging by holding shift. Closes #158.

Add option to select chunks/regions in a paint brush style

---

build.gradle
src/main/java/net/querz/mcaselector/changer/fields/CustomField.java
src/main/java/net/querz/mcaselector/filter/filters/CustomFilter.java

Switch from JavaScript to Groovy for custom filter and custom field changer.

Switch custom filter and custom field changer from JavaScript to Groovy

---

src/main/resources/lang/uk_UA.txt

Ukrainian localization for program.

add ukrainian localization

---

src/main/resources/lang/hu_HU.txt

Add Hungarian Language

---

src/main/java/net/querz/mcaselector/version/anvil118/Anvil118ChunkFilter.java
src/main/java/net/querz/mcaselector/version/anvil119/Anvil119ChunkFilter.java

I've had problems with block filling on my side. I've investigated the problem and created a fix. I saw that someone else (issue #425 ) had the same problem as me and with my version it replaces the blocks well.

Fix issue #425

---

src/main/java/net/querz/mcaselector/changer/FieldType.java
src/main/java/net/querz/mcaselector/changer/fields/CompressionField.java

Allows you to explicitly change the compression type to any supported one.

Add field to set compression type
